create table if not exists contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now()
);

alter table contacts enable row level security;

drop policy if exists "Allow public read contacts" on contacts;

create policy "Allow public read contacts"
on contacts
for select
to anon
using (true);

insert into contacts (name, phone) values
  ('Marcelo', '5511999999999'),
  ('Ana', '5511988888888'),
  ('Joao', '5511977777777');
